### ISSUE TITLE
Way to convert OpenDiS output data files to vtk?

### ISSUE THREAD

**Issue by ParadoxPrism117** [OpenDiS/OpenDiS#4]
Hi OpenDiS team,

I just recently installed this and have been going through the provided examples. 

I see that Ovito is mentioned as a visualization tool in the tutorial, but I wanted to ask if it was possible to convert the output files from .data format to .vtk format so that they could be visualized in something like Paraview? Does someone know of a script already out there that performs that function?

**Comment by nrbertin** [comment]
Hi,

I have added pyexadis utility function write_vtk() in commit LLNL/exadis@b142636. With this you should be able to convert .data files to .vtk files for visualization in Paraview, e.g.

```
import pyexadis
from pyexadis_utils import read_paradis, write_vtk
pyexadis.initialize()

N = read_paradis('config.data')
write_vtk(N, 'config.vtk')
```

I hope this helps.

**Comment by ParadoxPrism117** [comment]
Thanks! And this is something I put into a post-processing python script? Do I need to have OpenDiS running to use this?

**Comment by nrbertin** [comment]
Right now it is meant to be used as a post-processing step, i.e. you first run a simulation that generates .data files, and then convert these .data files to .vtk files for visualization.

If you really want to generate the .vtk files directly during a simulation run, then you can always use a modified version of the `SimulateNetwork` driver class from ExaDiS where you add something like
```
from pyexadis_utils import write_vtk
write_vtk(N, os.path.join(self.write_dir, 'config.%d.vtk'%(tstep+1)))
```
after [line 792](https://github.com/LLNL/exadis/blob/main/python/pyexadis_base.py#L792). I may add this as a permanent feature in the future.

**Comment by ParadoxPrism117** [comment]
Is there a specific place I can import pyexadis from?

**Comment by nrbertin** [comment]
Library pyexadis is built during compilation of the code. To compile, follow the instructions at [Compilation](https://opendis.github.io/OpenDiS/installation/compilation/compilation_overview.html). After successful compilation, the library will be located in `${OPENDIS_DIR}/core/exadis/python`. From there you should be able to import it after its path is properly added, e.g.
```
# add path to python
pyexadis_path = '/path/to/OpenDiS/core/exadis/python/'
if not pyexadis_path in sys.path: sys.path.append(pyexadis_path)

# import pyexadis
import pyexadis
```

**Comment by ParadoxPrism117** [comment]
I do not see a pyexadis.py file in my python folder. I only have pyexadis_base.py and pyexadis_utils.py files

**Comment by nrbertin** [comment]
There is no file pyexadis.py. A successful compilation of the code should produce shared library file `pyexadis.cpython-*.so` in the folder. This is the library that will be loaded when calling `import pyexadis` from python.

**Comment by ParadoxPrism117** [comment]
I got it to work, thanks for the help!
