### ISSUE TITLE
Issue with Collision Definition in Example Scripts

### ISSUE THREAD

**Issue by ParadoxPrism117** [OpenDiS/OpenDiS#6]
Hi,

I noticed today when I tried to run the example python scripts now that they fail due to an error on the collision line. I have only tried the frank-read source and strain hardening examples, but I assume the issue is the same for the other examples too. Has the syntax on the collision definition changed with the most recent update?

This is the output I get when trying to run the file:

<frozen importlib._bootstrap>:488: RuntimeWarning: The global interpreter lock (GIL) has been enabled to load module 'pyexadis', which has not declared that it can run safely without the GIL. To override this behavior and keep the GIL disabled (at your own risk), run with PYTHON_GIL=0 or -Xgil=0.
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false

Host Parallel Execution Space:
  KOKKOS_ENABLE_OPENMP: yes

OpenMP Runtime Configuration:
Kokkos::OpenMP thread_pool_topology[ 1 x 28 x 1 ]
init_frank_read_src_loop: length = 125.000000
Setting rtol to 0.250000
Setting rtol to 0.250000
Traceback (most recent call last):
  File "/home/kzimins/projects/opendis/examples/02_frank_read_src/test_frank_read_src_exadis.py", line 68, in <module>
    main()
    ~~~~^^
  File "/home/kzimins/projects/opendis/examples/02_frank_read_src/test_frank_read_src_exadis.py", line 52, in main
    collision = Collision(collision_mode='Retroactive', state=state)
  File "/home/kzimins/projects/opendis/core/exadis/python/pyexadis_base.py", line 515, in __init__
    self.collision = pyexadis.make_collision(collision_mode, params=params)
                     ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: make_collision(): incompatible function arguments. The following argument types are supported:
    1. (params: pyexadis.Params) -> pyexadis.Collision

Invoked with: 'Retroactive'; kwargs: params=<pyexadis.Params object at 0x40875566450>

**Comment by nrbertin** [comment]
Hi,

At this stage, OpenDiS is still under active development and subject to frequent updates that may trigger breaking changes (e.g. I have indeed recently introduced a change to the pyexadis collision binding).

In most cases, any such issues should be fixed by first pulling the latest version code and submodules (i.e. exadis)
```
cd ${OPENDIS_DIR}
git pull
git submodule update --init --recursive
```
and then rebuilding the pyexadis library from the now updated ExaDiS source
```
cd build
make -j8
```
Let me know if you're still seeing this issue after these steps.

**Comment by ParadoxPrism117** [comment]
Everything seems to be working again now, thanks for the quick fix!
